spring.application.name=usernest

# ===============================
# DATABASE CONFIG (H2 - FILE BASED)
# ===============================
spring.datasource.url=jdbc:h2:file:./data/usernest
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# SERVER PORT (IMPORTANT FOR DEPLOYMENT)
# ===============================
server.port=${PORT:8080}